config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :create, :edit, :update, :destroy]
  resources :verses

  root 'verses#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :verses
end

app/models/verse.rb
class Verse < ApplicationRecord
  def adjust_score(adjustment) 
    self.score += adjustment
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :uid)
    end
end

app/controllers/verses_controller.rb
class VersesController < ApplicationController
  before_action :set_verse, only: [:show, :edit, :update, :destroy]

  # GET /verses
  # GET /verses.json
  def index
    @verses = Verse.all
  end

  # GET /verses/1
  # GET /verses/1.json
  def show
  end

  # GET /verses/new
  def new
    @verse = Verse.new
  end

  # GET /verses/1/edit
  def edit
  end

  # POST /verses
  # POST /verses.json
  def create
    @verse = Verse.new(verse_params)

    respond_to do |format|
      if @verse.save
        format.html { redirect_to @verse, notice: 'Verse was successfully created.' }
        format.json { render :show, status: :created, location: @verse }
      else
        format.html { render :new }
        format.json { render json: @verse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verses/1
  # PATCH/PUT /verses/1.json
  def update
    respond_to do |format|
      if @verse.update(verse_params)
        format.html { redirect_to @verse, notice: 'Verse was successfully updated.' }
        format.json { render :show, status: :ok, location: @verse }
      else
        format.html { render :edit }
        format.json { render json: @verse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verses/1
  # DELETE /verses/1.json
  def destroy
    @verse.destroy
    respond_to do |format|
      format.html { redirect_to verses_url, notice: 'Verse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verse
      @verse = Verse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verse_params
      params.require(:verse).permit(:lyrics, :song, :artist, :album, :year, :score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/verse_helper.rb
module VerseHelper
end

app/helpers/verses_helper.rb
module VersesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Versesversus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :uid %>
    <%= form.text_field :uid, id: :user_uid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.uid %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/verses/_form.html.erb
<%= form_with(model: verse, local: true) do |form| %>
  <% if verse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(verse.errors.count, "error") %> prohibited this verse from being saved:</h2>

      <ul>
      <% verse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lyrics %>
    <%= form.text_field :lyrics, id: :verse_lyrics %>
  </div>

  <div class="field">
    <%= form.label :song %>
    <%= form.text_field :song, id: :verse_song %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :verse_artist %>
  </div>

  <div class="field">
    <%= form.label :album %>
    <%= form.text_field :album, id: :verse_album %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year, id: :verse_year %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score, id: :verse_score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/verses/edit.html.erb
<h1>Editing Verse</h1>

<%= render 'form', verse: @verse %>

<%= link_to 'Show', @verse %> |
<%= link_to 'Back', verses_path %>

app/views/verses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Verses</h1>

<table>
  <thead>
    <tr>
      <th>Lyrics</th>
      <th>Artist</th>
      <th>Song</th>
      <th>Album</th>
      <th>Year</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @verses.each do |verse| %>
      <tr>
        <td><%=verse.lyrics%></td>
        <td><%=verse.artist%></td>
        <td><%=verse.song%></td>
        <td><%=verse.album%></td>
        <td><%=verse.year%></td>
        <td><%=verse.score%></td>
        <td><%= link_to 'Show', verse_path(verse.id) %></td>
        <td><%= link_to 'Edit', edit_verse_path(verse) %></td>
        <td><%= link_to 'Destroy', verse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Verse', new_verse_path %>

app/views/verses/new.html.erb
<h1>New Verse</h1>

<%= render 'form', verse: @verse %>

<%= link_to 'Back', verses_path %>

app/views/verses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lyrics:</strong>
  <%= @verse.lyrics %>
</p>

<p>
  <strong>Song:</strong>
  <%= @verse.song %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @verse.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @verse.album %>
</p>

<p>
  <strong>Year:</strong>
  <%= @verse.year %>
</p>

<p>
  <strong>Score:</strong>
  <%= @verse.score %>
</p>

<%= link_to 'Edit', edit_verse_path(@verse) %> |
<%= link_to 'Back', verses_path %>